spin_manifest_version = 2

[application]
name = "aos_web_page"
version = "0.1.0"
description = "Advent of Spin 2022-02"

[[trigger.http]]
route = "/"
component = "aos-web-page"

[component.aos-web-page]
source = "target/wasm32-wasi/release/aos_web_page.wasm"
[component.aos-web-page.build]
command = "cargo build --target wasm32-wasi --release"