spin_manifest_version = 2

[application]
name = "todo"
version = "0.1.0"
authors = ["Oxide Byte"]
description = "Todo Fermyon Application"

[[trigger.http]]
route = "/ui/..."
component = "ui"

[[trigger.http]]
route = "/api/..."
component = "api"

[component.ui]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "todo_ui/dist/", destination = "/" }]

[component.ui.build]
command = "make ui"
watch = ["todo_ui/src/**/*.rs", "todo_ui/index.html", "todo/ui/Cargo.toml"]

[component.api]
source = "todo_api/target/wasm32-wasi/release/todo_api.wasm"
sqlite_databases = ["default"]

[component.api.build]
command = "make api"
watch = ["todo_api/src/**/*.rs", "todo_api/Cargo.toml"]